import { StyleSheet } from "react-native";
import { colors } from "@/constants/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.neutral[50],
  },
  scrollContainer: {
    paddingHorizontal: 24,
    paddingTop: 36,
    paddingBottom: 40,
  },
  header: {
    alignItems: "center",
    marginBottom: 32,
  },
  avatarContainer: {
    position: "relative",
    width: 100,
    height: 100,
    marginBottom: 16,
  },
  avatar: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 3,
    borderColor: colors.light.card,
    backgroundColor: colors.neutral[200],
  },
  avatarPlaceholder: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: colors.primary.light,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 3,
    borderColor: colors.light.card,
  },
  avatarPlaceholderText: {
    fontSize: 36,
    fontWeight: "700",
    color: colors.primary.default,
  },
  editBadge: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.primary.default,
    justifyContent: "center",
    alignItems: "center",
    // shadow
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  name: {
    fontSize: 22,
    fontWeight: "700",
    color: colors.neutral[900],
    marginBottom: 4,
  },
  email: {
    fontSize: 14,
    color: colors.neutral[500],
  },
  statsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 24,
    gap: 16,
  },
  statCard: {
    flex: 1,
    backgroundColor: colors.light.card,
    borderWidth: 1,
    borderColor: colors.neutral[200],
    borderRadius: 14,
    padding: 16,
    alignItems: "center",
    // shadow
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 1,
  },
  statValue: {
    fontSize: 20,
    fontWeight: "700",
    color: colors.neutral[900],
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: colors.neutral[500],
    fontWeight: "500",
  },
  progressCard: {
    backgroundColor: colors.light.card,
    borderWidth: 1,
    borderColor: colors.neutral[200],
    borderRadius: 14,
    padding: 20,
    marginBottom: 24,
    // shadow
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 1,
  },
  progressHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  progressTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.neutral[800],
  },
  progressValue: {
    fontSize: 14,
    fontWeight: "700",
    color: colors.primary.default,
  },
  progressBarBg: {
    width: "100%",
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.neutral[200],
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    borderRadius: 4,
    backgroundColor: colors.primary.default,
  },
  detailsCard: {
    backgroundColor: colors.light.card,
    borderWidth: 1,
    borderColor: colors.neutral[200],
    borderRadius: 14,
    padding: 20,
    marginBottom: 32,
    // shadow
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 1,
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.neutral[100],
  },
  detailRowLast: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 12,
    borderBottomWidth: 0,
  },
  detailLabel: {
    fontSize: 14,
    color: colors.neutral[500],
    fontWeight: "500",
  },
  detailValue: {
    fontSize: 14,
    color: colors.neutral[800],
    fontWeight: "600",
  },
  logoutButton: {
    borderColor: colors.error,
    borderWidth: 1.5,
    backgroundColor: "transparent",
  },
});
